/* Vendors the three Google Fonts families into assets/fonts/.

   Why: the stylesheet currently loads from fonts.googleapis.com, which puts
   two third-party DNS+TLS handshakes on the critical path before a single
   glyph can render — and it sits inside <body>, after </head>, so it blocks
   later than it should. Self-hosting removes both origins, makes the
   "runs offline" claim literally true, and lets the files be served
   immutable from the same origin as everything else.

   Only the latin and latin-ext subsets are kept. Turkish needs latin-ext
   (ğ İ ı ş and their capitals live in Latin Extended-A); cyrillic, greek
   and vietnamese are dead weight for an EN/TR page.

     node tools/fetch-fonts.mjs
*/
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'assets', 'fonts');

/* Exactly the families and weights index.html asks for today. */
const CSS_URL = 'https://fonts.googleapis.com/css2'
  + '?family=Archivo:wght@600;700'
  + '&family=Inter:wght@400;500;600'
  + '&family=JetBrains+Mono:wght@400;500'
  + '&display=swap';

/* Without a modern UA Google serves TTF instead of woff2. */
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';

const KEEP = new Set(['latin', 'latin-ext']);

fs.mkdirSync(OUT, { recursive: true });

const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error('Google Fonts CSS -> HTTP ' + res.status);
let css = await res.text();
if (!css.includes('woff2')) throw new Error('expected woff2; got a legacy format');

/* Google emits one @font-face per family/weight/subset, each preceded by a
   /* subset *\/ comment. Parse them as blocks so the subset name, the
   unicode-range and the src stay together. */
const blocks = css.split('/*').slice(1).map((b) => '/*' + b);

/* Parse first, name second. Archivo and Inter arrive as VARIABLE fonts:
   one file per subset serves every weight, and Google emits several
   @font-face rules pointing at the same URL. Naming a shared file after
   whichever weight happened to be parsed first produces
   `archivo-600-latin.woff2` for a file that also serves 700 — an invitation
   for someone to later delete it as a duplicate. Shared files get `-var`. */
const parsed = [];
for (const b of blocks) {
  const subset = (/^\/\*\s*([a-z-]+)\s*\*\//.exec(b) || [])[1];
  const url = (/src:\s*url\((https:\/\/[^)]+\.woff2)\)/.exec(b) || [])[1];
  if (!subset || !url) continue;
  parsed.push({
    b, subset, url,
    family: (/font-family:\s*'([^']+)'/.exec(b) || [])[1],
    weight: (/font-weight:\s*(\d+)/.exec(b) || [])[1],
    style: (/font-style:\s*(\w+)/.exec(b) || [])[1] || 'normal',
  });
}
const weightsPerUrl = new Map();
for (const p of parsed) {
  if (!weightsPerUrl.has(p.url)) weightsPerUrl.set(p.url, new Set());
  weightsPerUrl.get(p.url).add(p.weight);
}

const out = [];
const seen = new Map();
let kept = 0, skipped = 0, bytes = 0;

for (const p of parsed) {
  const { b, subset, url, family, weight, style } = p;
  if (!KEEP.has(subset)) { skipped++; continue; }

  const shared = weightsPerUrl.get(url).size > 1;
  const name = family.toLowerCase().replace(/\s+/g, '-')
    + '-' + (shared ? 'var' : weight) + (style === 'italic' ? 'i' : '') + '-' + subset + '.woff2';

  if (!seen.has(url)) {
    const r = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!r.ok) throw new Error(url + ' -> HTTP ' + r.status);
    const buf = Buffer.from(await r.arrayBuffer());
    /* woff2 files start with the signature 'wOF2' */
    if (buf.slice(0, 4).toString('latin1') !== 'wOF2') throw new Error(name + ' is not woff2');
    fs.writeFileSync(path.join(OUT, name), buf);
    seen.set(url, { name, bytes: buf.length, weights: [...weightsPerUrl.get(url)].sort(), sha256: crypto.createHash('sha256').update(buf).digest('hex') });
    bytes += buf.length;
  }
  const local = seen.get(url).name;
  out.push(b.replace(/\/\*[^*]*\*\/\s*/, '').replace(url, local).trim());
  kept++;
}

if (!kept) throw new Error('no @font-face blocks kept — the CSS format changed');

const header = [
  '/* Self-hosted from Google Fonts. Generated by tools/fetch-fonts.mjs —',
  ' * do not edit by hand.',
  ' *',
  ' * Source: ' + CSS_URL,
  ' * Subsets: latin, latin-ext (latin-ext carries Turkish ğ İ ı ş).',
  ' * Licence: SIL Open Font Licence 1.1 for all three families.',
  ' */',
  '',
].join('\n');

fs.writeFileSync(path.join(OUT, 'fonts.css'), header + out.join('\n\n') + '\n');
fs.writeFileSync(path.join(OUT, 'PROVENANCE.json'),
  JSON.stringify({ source: CSS_URL, subsets: [...KEEP], files: [...seen.values()] }, null, 2) + '\n');

console.log('  ' + kept + ' @font-face kept, ' + skipped + ' subsets skipped');
console.log('  ' + seen.size + ' woff2 files, ' + Math.round(bytes / 1024) + ' KB total');
console.log('\nassets/fonts/fonts.css written. SIL OFL 1.1.');
